config/routes.rb
Rails.application.routes.draw do
  resources :scores
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/score.rb
class Score < ApplicationRecord
  default_scope { order("centiseconds ASC") }

  after_create_commit { refresh_leaderboard }
  after_destroy_commit { refresh_leaderboard }

  def refresh_leaderboard
    leaderboard = Score.first(5)

    if leaderboard.include? self
      place = leaderboard.find_index(self) + 1
      msg = "#{self.name} is in #{place.ordinalize} place with #{self.time}"
      broadcast_append_to("notifications", target: "notification_list", partial: "notification", locals: {message: msg})
    end

    broadcast_update_to("scores", target: "leaderboard", partial: "leaderboard", locals: {scores: leaderboard})
  end

  def time
    cseconds = pad(centiseconds % 100)
    seconds = pad((centiseconds/100).to_i % 60)
    minutes = pad((centiseconds/100).to_i / 60)

    "#{minutes}:#{seconds}:#{cseconds}"
  end

  def pad(num)
    num.to_s.rjust(2, '0')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    @scores = Score.first(5)
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: %i[ show destroy ]

  # # GET /scores or /scores.json
  # def index
  #   @scores = Score.all
  # end

  # # GET /scores/1 or /scores/1.json
  # def show
  # end

  # # GET /scores/new
  # def new
  #   @score = Score.new
  # end

  # # GET /scores/1/edit
  # def edit
  # end

  # POST /scores or /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.turbo_stream
        format.html { redirect_to score_url(@score), notice: "Score was successfully created." }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # # PATCH/PUT /scores/1 or /scores/1.json
  # def update
  #   respond_to do |format|
  #     if @score.update(score_params)
  #       format.html { redirect_to score_url(@score), notice: "Score was successfully updated." }
  #       format.json { render :show, status: :ok, location: @score }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @score.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /scores/1 or /scores/1.json
  # def destroy
  #   @score.destroy

  #   respond_to do |format|
  #     format.html { redirect_to scores_url, notice: "Score was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def score_params
      params.require(:score).permit(:name, :centiseconds)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/application/_leaderboard.html.erb
<table class="min-w-full divide-y divide-gray-300">
  <tbody class="divide-y divide-gray-200">
    <% scores.each.with_index(1) do |score, idx| %>
      <tr>
        <td class="whitespace-nowrap text-sm text-gray-500 font-bold"><%= idx.ordinalize %></td>
        <td class="whitespace-nowrap pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= score.name %></td>
        <td class="whitespace-nowrap px-3 text-sm text-gray-500"><%= score.time %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/application/_notification.html.erb
<% if message.present? %>
  <div data-controller="notification" class="pointer-events-auto w-full max-w-sm overflow-hidden rounded-lg bg-white shadow-lg ring-1 ring-black ring-opacity-5">
    <div class="p-4">
      <div class="flex items-start">
        <div class="ml-3 w-0 flex-1 pt-0.5">
          <p class="text-sm font-medium text-gray-900"><%= message %></p>
        </div>
        <div class="ml-4 flex flex-shrink-0">
          <button data-action="click->notification#remove" type="button" class="inline-flex rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
            <span class="sr-only">Close</span>
            <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/application/_timer.html.erb
<div data-controller="game" class="my-7 font-bold text-4xl mx-auto" style="width: 500px;">
  <%= turbo_frame_tag "new_score" do %>
    <%= form_with model: Score.new, data: { "game-target": "form" } do |form| %>
      <%= form.text_field :name, class: "mx-auto block w-full border-0", style: "background-color: #ede6e3; font-size: .9em;", placeholder: "Your name", value: "Guest-#{SecureRandom.hex(3)}" %>
      <%= form.hidden_field :centiseconds, data: { "game-target": "centisecondsOutput" } %>
    <% end %>
  <% end %>

  <div class="mx-auto w-full" style="padding: .5rem .75rem;">
    <span data-game-target="minutes">00</span>:<span data-game-target="seconds">00</span>:<span data-game-target="centiseconds">00</span>
  </div>
</div>

app/views/application/index.html.erb
<%= turbo_stream_from "notifications" %>
<%= turbo_frame_tag "notifications" do %>
  <!-- Global notification live region, render this permanently at the end of the document -->
  <div aria-live="assertive" class="pointer-events-none fixed inset-0 flex items-end px-4 py-6 sm:items-start sm:p-6">
    <div id="notification_list" class="flex w-full flex-col items-center space-y-4 sm:items-end">
      <!--
        Notification panel, dynamically insert this into the live region when it needs to be displayed

        Entering: "transform ease-out duration-300 transition"
          From: "translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2"
          To: "translate-y-0 opacity-100 sm:translate-x-0"
        Leaving: "transition ease-in duration-100"
          From: "opacity-100"
          To: "opacity-0"
      -->
      <%= render partial: "notification", locals: { message: "" } %>
    </div>
  </div>
<% end %>

<%= render partial: "timer" %>

<div id="center">
  <div id="game">
    <div id="maze">
      <div id="end"></div>
    </div>
    <div id="joystick">
      <div class="joystick-arrow"></div>
      <div class="joystick-arrow"></div>
      <div class="joystick-arrow"></div>
      <div class="joystick-arrow"></div>
      <div id="joystick-head"></div>
    </div>
    <div id="note">
      Click The Joy-Stick To Start!
      <p>Move Every Ball To The Center. Ready For Hard Mode? Press H</p>
    </div>
  </div>
</div>

<%= turbo_stream_from "scores" %>
<%= turbo_frame_tag "scores" do %>
  <div id="leaderboard" class="my-24 mx-auto" style="width: 500px;">
    <%= render partial: "leaderboard", locals: {scores: @scores} %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TiltMaze</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body>
    <main class="container mx-auto pt-28 px-5">
      <%= yield %>
    </main>
    <%= javascript_include_tag('tilt_maze') %>
  </body>
</html>

app/views/scores/_form.html.erb
<%= form_with(model: score) do |form| %>
  <% if score.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
        <% score.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :centiseconds, style: "display: block" %>
    <%= form.number_field :centiseconds %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/scores/_score.html.erb
<div id="<%= dom_id score %>">
  <p>
    <strong>Name:</strong>
    <%= score.name %>
  </p>

  <p>
    <strong>Centiseconds:</strong>
    <%= score.centiseconds %>
  </p>

</div>

app/views/scores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Scores</h1>

<div id="scores">
  <% @scores.each do |score| %>
    <%= render score %>
    <p>
      <%= link_to "Show this score", score %>
    </p>
  <% end %>
</div>

<%= link_to "New score", new_score_path %>

app/views/scores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @score %>

<div>
  <%= link_to "Edit this score", edit_score_path(@score) %> |
  <%= link_to "Back to scores", scores_path %>

  <%= button_to "Destroy this score", @score, method: :delete %>
</div>